### PR TITLE
Add script to ensure concepts have numeric PIH mapping

### PR DESCRIPTION
**Pull request by brandones**

### CODE REVIEW

**Review by mseaton — APPROVED** [review]
Looks good to me generally, I assume you've tested it.  Defer to @lnball for her broader perspective.

**Comment by lnball** [comment]
LGTM.  Is this from the scripts I wrote and added to the ticket?  

I tested on concepts server and looks like every concept has a numeric mapping.

Thanks @brandones

**Review by lnball — APPROVED** [review]
LGTM

**Comment by brandones** [comment]
Yes @lnball , this is your code.

**Pull request merged**
