### PR TITLE
UHM-6298 Change text for resident assistant

### PR DESCRIPTION
**Pull request by lnball**

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
LGTM, thanks @lnball !

**Review by louidorjp — COMMENTED** [review]
resident_pic1

**Review by louidorjp — APPROVED** [review]

**Comment by lnball** [comment]
@mogoodrich Can you help me "resolve conflicts" on github?  It's not clear how to do on the UI.

**Comment by mogoodrich** [comment]
@lnball  i think it should be straightforward to resolve via the UI... if you click on Resolve conflicts, it will show you the conflicts, looks like there is only one, you just need to manually edit the conflict to only have the lines you actually want:

**Pull request merged**
