### PR TITLE
UHM-6190 Liquibase change for removing obsolete reference mappings an…

### PR DESCRIPTION
**Pull request by lnball**
…d sources

### CODE REVIEW

**Review by brandones — APPROVED** [review]
LGTM, assuming you've tested this locally without incident :)

**Comment by lnball** [comment]
@brandones I did test locally on my SDK.  The changeset ran but I didn't have any of those mappings.

**Comment by brandones** [comment]
Probably best if @mseaton or @mogoodrich look at it to make sure it's not subject to that subquery bug they ran into, in that case.

**Review by mseaton — APPROVED** [review]
Looks good to me.

**Pull request merged**
