### PR TITLE
UHM-5508: When choosing a Disposition of "Death", death date should b…

### PR DESCRIPTION
**Pull request by mogoodrich**
…e required

(apply to COVID, Mental Health, Delivery and OB-GYN forms)

### CODE REVIEW

**Comment by mogoodrich** [comment]
Manually copying the hack javascript I wrote to all the forms that have the encounterDisposition tag... ideally, long-term, we'd update the Encounter Disposition tag to have an attribute that makes the sub-categories required.

**Comment by lnball** [comment]
Looks fine but I don't see how the javascript requires and relates to the death date.  Someone else should review (ie. Brandon) ;)

**Comment by mogoodrich** [comment]
Thanks @lnball ... yeah, I flagged @brandones  as well... but, good point... this JavaScript makes any field related to a disposition required, not just "Date of Death"... ie, "Admission Location" if they select a disposition of Admit.

**Comment by brandones** [comment]
File as motivation for https://pihemr.atlassian.net/browse/UHM-5375 ...

**Comment by brandones** [comment]
I feel like I already reviewed this code last week... this is a copy-paste from somewhere?

**Comment by mogoodrich** [comment]
yeah, more or less a copy-paste, so probably no need to review in detail, I tested each one...

**Review by brandones — APPROVED** [review]
Cursory review, but LGTM.

**Pull request merged**
