### PR TITLE
UHM-6839: Set "Reason for Change" when substituting drugs

### PR DESCRIPTION
**Pull request by mogoodrich**
New configuration for substitution questions answered provided by PIH EMR

### CODE REVIEW

**Review by mseaton — APPROVED** [review]
LGTM, assuming these are the right uuids.  Note, I'm not a fan of configuration by uuid in general, I'd rather we be able to configure by mapping or something a little more clearly representative of the concept semantically

**Comment by lnball** [comment]
LGTM.  uuids are correct but as Mike points out -- hard to read.

**Comment by mogoodrich** [comment]
Yeah, agreed re:uuid... those this seems to be the general configuration pattern in O3... let me dig a little deeper and see if there's any utility methods to fetch by mappings, and, if not, ticket in the overall O3 project to add them.

**Comment by mogoodrich** [comment]
Started a thread here about the best way to search/reference valueset here: https://talk.openmrs.org/t/searching-for-valuesets/38480

Going to merge this in with the uuid solution for now to keep things moving forward.

**Pull request merged**
