### PR TITLE
Fix liquibase change author

### PR DESCRIPTION
**Pull request by brandones**

### CODE REVIEW

**Review by mogoodrich — COMMENTED** [review]
Not sure if this will break the checksum on the changeset, did you test?  (I'd be fine with leaving this as it is, you could just add a  comment before if you wanted.

**Comment by brandones** [comment]
I tested and it didn't cause any errors. It's idempotent, anyway.

**Comment by mogoodrich** [comment]
Cool... yeah, I wasn't worried about the changeset itself running twice...  just if liquibase notices a change to changeset, it fails automatically, and I didn't know if was the case for author as well, I'm fine with merging if it worked...

**Comment by mogoodrich** [comment]
Cool... yeah, I wasn't worried about the changeset itself running twice...  just if liquibase notices a change to changeset, it fails automatically, and I didn't know if was the case for author as well, I'm fine with merging if it worked...

**Pull request merged**
